### ISSUE TITLE
ROS version

### ISSUE THREAD

**Issue by nikfio** [jhu-asco/dsl_gridsearch#2]
Hello everyone,
what ROS version are you using to compile this package?

I'm getting this kind of errors:

error: wrong number of template arguments (2, should be 3)
   nav_msgs::Path dslPathToRosMsg(const dsl::GridPath<2, float>& dsl_path);

**Comment by msheckells** [comment]
It is not an issue with your ROS version.  This package was based on an older version of the dsl library.  Checkout commit 61cf588668309e87de209cd95f03a0f792a16c33 when building dsl and it should work.  I updated the README to give this information.

**Comment by nikfio** [comment]
Everything works, thank you a lot!
